version: '3'
networks:
  elk:
    external: true
services:
  project_front:
    container_name: project_front
    restart: always
#    image: registry.gitlab.com/getgaingroup/*registry-path*:latest
    ports:
      - _CONTAINER_OUT_PORT_:80
    networks:
      - elk
    volumes:
#      - /var/www/*project-folder*/uploads:/uploads
